apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: user-service
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      run: user-service
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
      - image: gcr.io/sixth-syntax-438916-q0/user-service:latest
        name: user-service
        ports:
        - containerPort: 3131